
-- CLASS# 4 (APPLY CONDITIONS TO TABLE).

/* WHERE CONDITION */
SELECT * FROM Std WHERE AGE>=20;

/* AS CONDITION */
SELECT NAME AS STUDENT_NAME FROM Std;

/* AND CONDITION */
SELECT * FROM Std WHERE AGE<=25 AND ADMISSION_DATE<='2024-01-01';

/* OR CONDITION */
SELECT * FROM Std WHERE AGE>=28 OR ADMISSION_DATE>='2020-01-01';

/* NOT CONDITION */
SELECT * FROM Std WHERE NOT AGE<=25 OR NAME='Hamza';

/* IN CONDITION */
SELECT * FROM Std WHERE NAME IN ('Shayan','Zaid');